[package]
authors = ["The Winch Project Developers"]
name = "winch-filetests"
description = "Tests for the Winch compiler based on a set of known valid files"
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/bytecodealliance/wasmtime"
version = "0.0.0"
publish = false
edition.workspace = true

[lints]
workspace = true

[dependencies]
winch-test-macros = {workspace = true}
target-lexicon = { workspace = true }
winch-codegen = { workspace = true, features = ['all-arch'] }
wasmtime-environ = { workspace = true }
anyhow = { workspace = true }
wat = { workspace = true }
similar = { workspace = true }
toml = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
cranelift-codegen = { workspace = true }
capstone = { workspace = true }
wasmparser = { workspace = true }
