[package]
name = "example-component-wasm"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition = "2021"
publish = false

[dependencies]
wit-bindgen = { workspace = true, default-features = true }

[lib]
path = "guest.rs"
name = "guest"
crate-type = ["cdylib"]
